### ISSUE TITLE
Windows aplication doesn't work

### ISSUE THREAD

**Issue by UlisesLafuente** [santifaster/Cronotareas#1]
The windows application does not start. The error window reads as follows: 

```
Error: Couldn't load project data at path ".", is the .pck file missing? 
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension)
```

**Comment by santifaster** [comment]
I'm seeing that I missed to upload the windows version to itch with the .pck file in the v0.2.1, it should be solved now if you redownload it.

**Comment by santifaster** [comment]
I have tested it on windows 10 with the new download and it works, so unless there is another related issue I will close this issue.
